services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: passwd
      PGUSER: postgres

  app:
    image: simple2b/robert-cohen-backend:2.0
    restart: always
    command: sh ./start_web.sh
    environment:
      APP_ENV: production
      ALCHEMICAL_DATABASE_URL: postgresql://postgres:passwd@db:5432/db
      NEXT_URL: ${NEXT_URL:-https://diemsondemand.com}
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 127.0.0.1:8001:8000

  api:
    image: simple2b/robert-cohen-backend:2.0
    restart: always
    command: sh ./start_api.sh
    environment:
      APP_ENV: production
      IS_API: "true"
      ALCHEMICAL_DATABASE_URL: postgresql://postgres:passwd@db:5432/db
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 127.0.0.1:8002:8000

  front:
    image: simple2b/robert-cohen-front-prod:1.1
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:3000:3000

volumes:
  db_data:
